# Example configuration for MCP with direct API access
# Copy this to your project root as config.yml and update as needed

# No EAS configuration needed for direct access
# Simply omit the 'eas' section

# Model configurations using direct API access
models:
    # OpenAI models
    '1':
        provider: openai
        type: chat
        model_name: gpt-4.1-2025-04-14
        # Uses OPENAI_API_KEY from environment
 
# MCP Server Configuration
mcp:
    servers:
        # Example MCP server included in this directory
        example:
            command: python
            args: ["examples/mcp/simple_mcp_server.py"]
            transport: stdio
            
        # You can add multiple MCP servers
        # math_tools:
        #     command: python
        #     args: ["path/to/math_server.py"]
        #     transport: stdio
        #     
        # web_tools:
        #     command: node
        #     args: ["path/to/web_tools.js"]
        #     transport: stdio